DELETE FROM T_VBP_COMMONLY_USED_CONTACT WHERE ID in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15);

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (1, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (2, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (3, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (4, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (5, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (6, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (7, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (8, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (9, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (10, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (11, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (12, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (13, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (14, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (15, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

