DELETE FROM T_VBP_COMMONLY_USED_CONTACT WHERE ID = 1;
DELETE FROM T_VBP_COMMONLY_USED_CONTACT WHERE ID = 2;

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (1, '220978', 'aaaa', 'PASSPORT', 'rghj', TIMESTAMP'2012-03-12', '', 'FEMALE', '');

insert into T_VBP_COMMONLY_USED_CONTACT (ID, MC_MEMBER_CODE, NAME, IDENTITY_TYPE, IDENTITY_NO, BIRTHDAY, PHONE, GENDER, CARD_NO)
values (2, '220978', 'stenven', 'NOTHING', '', TIMESTAMP'2012-04-12', '', 'FEMALE', '');
