//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.28 at 03:37:52 PM CST 
//


package com.jje.membercenter.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="listofcontact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contact">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="call" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="post" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="travel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="fashion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="movie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="music" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="culture" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="shopping" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sports" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="muslim" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="vegetarian" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="game" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="mag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="emailbill" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="emailepro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="emailinvet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="emailsubpartn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="emailsubpro" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "response")
public class MemberHobbyResponse {

    @XmlElement(required = true)
    protected MemberHobbyResponse.Head head;
    @XmlElement(required = true)
    protected MemberHobbyResponse.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link MemberHobbyResponse.Head }
     *     
     */
    public MemberHobbyResponse.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberHobbyResponse.Head }
     *     
     */
    public void setHead(MemberHobbyResponse.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link MemberHobbyResponse.Body }
     *     
     */
    public MemberHobbyResponse.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberHobbyResponse.Body }
     *     
     */
    public void setBody(MemberHobbyResponse.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="listofcontact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contact">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="call" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sms" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="post" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="travel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="fashion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="movie" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="music" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="culture" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="shopping" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sports" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="muslim" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="vegetarian" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="game" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="mag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="emailbill" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="emailepro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="emailinvet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="emailsubpartn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="emailsubpro" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "membid",
        "listofcontact"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected MemberHobbyResponse.Body.Listofcontact listofcontact;

        /**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the listofcontact property.
         * 
         * @return
         *     possible object is
         *     {@link MemberHobbyResponse.Body.Listofcontact }
         *     
         */
        public MemberHobbyResponse.Body.Listofcontact getListofcontact() {
            return listofcontact;
        }

        /**
         * Sets the value of the listofcontact property.
         * 
         * @param value
         *     allowed object is
         *     {@link MemberHobbyResponse.Body.Listofcontact }
         *     
         */
        public void setListofcontact(MemberHobbyResponse.Body.Listofcontact value) {
            this.listofcontact = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contact">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="call" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="sms" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="post" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="travel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="fashion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="movie" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="music" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="culture" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="shopping" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="sports" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="muslim" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="vegetarian" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="game" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="mag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="emailbill" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="emailepro" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="emailinvet" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="emailsubpartn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="emailsubpro" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contact"
        })
        public static class Listofcontact {

            @XmlElement(required = true)
            protected MemberHobbyResponse.Body.Listofcontact.Contact contact;

            /**
             * Gets the value of the contact property.
             * 
             * @return
             *     possible object is
             *     {@link MemberHobbyResponse.Body.Listofcontact.Contact }
             *     
             */
            public MemberHobbyResponse.Body.Listofcontact.Contact getContact() {
                return contact;
            }

            /**
             * Sets the value of the contact property.
             * 
             * @param value
             *     allowed object is
             *     {@link MemberHobbyResponse.Body.Listofcontact.Contact }
             *     
             */
            public void setContact(MemberHobbyResponse.Body.Listofcontact.Contact value) {
                this.contact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="call" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="sms" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="post" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="travel" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="fashion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="movie" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="music" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="culture" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="shopping" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="sports" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="public" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="muslim" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="vegetarian" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="game" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="mag" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="emailbill" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="emailepro" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="emailinvet" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="emailsubpartn" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="emailsubpro" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "conpriflag",
                "call",
                "sms",
                "email",
                "fax",
                "post",
                "travel",
                "fashion",
                "movie",
                "music",
                "culture",
                "shopping",
                "sports",
                "_public",
                "muslim",
                "vegetarian",
                "game",
                "mag",
                "emailbill",
                "emailepro",
                "emailinvet",
                "emailsubpartn",
                "emailsubpro"
            })
            public static class Contact {

                @XmlElement(required = true)
                protected String conpriflag;
                @XmlElement(required = true)
                protected String call;
                @XmlElement(required = true)
                protected String sms;
                @XmlElement(required = true)
                protected String email;
                @XmlElement(required = true)
                protected String fax;
                @XmlElement(required = true)
                protected String post;
                @XmlElement(required = true)
                protected String travel;
                @XmlElement(required = true)
                protected String fashion;
                @XmlElement(required = true)
                protected String movie;
                @XmlElement(required = true)
                protected String music;
                @XmlElement(required = true)
                protected String culture;
                @XmlElement(required = true)
                protected String shopping;
                @XmlElement(required = true)
                protected String sports;
                @XmlElement(name = "public", required = true)
                protected String _public;
                @XmlElement(required = true)
                protected String muslim;
                @XmlElement(required = true)
                protected String vegetarian;
                @XmlElement(required = true)
                protected String game;
                @XmlElement(required = true)
                protected String mag;
                @XmlElement(required = true)
                protected String emailbill;
                @XmlElement(required = true)
                protected String emailepro;
                @XmlElement(required = true)
                protected String emailinvet;
                @XmlElement(required = true)
                protected String emailsubpartn;
                @XmlElement(required = true)
                protected String emailsubpro;

                /**
                 * Gets the value of the conpriflag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConpriflag() {
                    return conpriflag;
                }

                /**
                 * Sets the value of the conpriflag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConpriflag(String value) {
                    this.conpriflag = value;
                }

                /**
                 * Gets the value of the call property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCall() {
                    return call;
                }

                /**
                 * Sets the value of the call property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCall(String value) {
                    this.call = value;
                }

                /**
                 * Gets the value of the sms property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSms() {
                    return sms;
                }

                /**
                 * Sets the value of the sms property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSms(String value) {
                    this.sms = value;
                }

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

                /**
                 * Gets the value of the fax property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFax() {
                    return fax;
                }

                /**
                 * Sets the value of the fax property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFax(String value) {
                    this.fax = value;
                }

                /**
                 * Gets the value of the post property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPost() {
                    return post;
                }

                /**
                 * Sets the value of the post property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPost(String value) {
                    this.post = value;
                }

                /**
                 * Gets the value of the travel property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTravel() {
                    return travel;
                }

                /**
                 * Sets the value of the travel property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTravel(String value) {
                    this.travel = value;
                }

                /**
                 * Gets the value of the fashion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFashion() {
                    return fashion;
                }

                /**
                 * Sets the value of the fashion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFashion(String value) {
                    this.fashion = value;
                }

                /**
                 * Gets the value of the movie property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMovie() {
                    return movie;
                }

                /**
                 * Sets the value of the movie property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMovie(String value) {
                    this.movie = value;
                }

                /**
                 * Gets the value of the music property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMusic() {
                    return music;
                }

                /**
                 * Sets the value of the music property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMusic(String value) {
                    this.music = value;
                }

                /**
                 * Gets the value of the culture property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCulture() {
                    return culture;
                }

                /**
                 * Sets the value of the culture property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCulture(String value) {
                    this.culture = value;
                }

                /**
                 * Gets the value of the shopping property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShopping() {
                    return shopping;
                }

                /**
                 * Sets the value of the shopping property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShopping(String value) {
                    this.shopping = value;
                }

                /**
                 * Gets the value of the sports property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSports() {
                    return sports;
                }

                /**
                 * Sets the value of the sports property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSports(String value) {
                    this.sports = value;
                }

                /**
                 * Gets the value of the public property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPublic() {
                    return _public;
                }

                /**
                 * Sets the value of the public property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPublic(String value) {
                    this._public = value;
                }

                /**
                 * Gets the value of the muslim property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMuslim() {
                    return muslim;
                }

                /**
                 * Sets the value of the muslim property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMuslim(String value) {
                    this.muslim = value;
                }

                /**
                 * Gets the value of the vegetarian property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVegetarian() {
                    return vegetarian;
                }

                /**
                 * Sets the value of the vegetarian property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVegetarian(String value) {
                    this.vegetarian = value;
                }

                /**
                 * Gets the value of the game property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGame() {
                    return game;
                }

                /**
                 * Sets the value of the game property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGame(String value) {
                    this.game = value;
                }

                /**
                 * Gets the value of the mag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMag() {
                    return mag;
                }

                /**
                 * Sets the value of the mag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMag(String value) {
                    this.mag = value;
                }

                /**
                 * Gets the value of the emailbill property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailbill() {
                    return emailbill;
                }

                /**
                 * Sets the value of the emailbill property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailbill(String value) {
                    this.emailbill = value;
                }

                /**
                 * Gets the value of the emailepro property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailepro() {
                    return emailepro;
                }

                /**
                 * Sets the value of the emailepro property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailepro(String value) {
                    this.emailepro = value;
                }

                /**
                 * Gets the value of the emailinvet property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailinvet() {
                    return emailinvet;
                }

                /**
                 * Sets the value of the emailinvet property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailinvet(String value) {
                    this.emailinvet = value;
                }

                /**
                 * Gets the value of the emailsubpartn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailsubpartn() {
                    return emailsubpartn;
                }

                /**
                 * Sets the value of the emailsubpartn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailsubpartn(String value) {
                    this.emailsubpartn = value;
                }

                /**
                 * Gets the value of the emailsubpro property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmailsubpro() {
                    return emailsubpro;
                }

                /**
                 * Sets the value of the emailsubpro property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmailsubpro(String value) {
                    this.emailsubpro = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "reqtime",
        "systype",
        "retcode",
        "retmsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String transcode;
        @XmlElement(required = true)
        protected String reqtime;
        @XmlElement(required = true)
        protected String systype;
        @XmlElement(required = true)
        protected String retcode;
        @XmlElement(required = true)
        protected String retmsg;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranscode(String value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the reqtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqtime() {
            return reqtime;
        }

        /**
         * Sets the value of the reqtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqtime(String value) {
            this.reqtime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

        /**
         * Gets the value of the retcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetcode() {
            return retcode;
        }

        /**
         * Sets the value of the retcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetcode(String value) {
            this.retcode = value;
        }

        /**
         * Gets the value of the retmsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetmsg() {
            return retmsg;
        }

        /**
         * Sets the value of the retmsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetmsg(String value) {
            this.retmsg = value;
        }

    }

}
