//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.16 at 06:42:11 PM CST 
//


package com.jje.membercenter.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bindflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="passwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pwdquestion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="pwdanswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="listofcontact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contact" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="listofpersonaladdress">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "request")
public class MemberBindRequest {

    @XmlElement(required = true)
    protected MemberBindRequest.Head head;
    @XmlElement(required = true)
    protected MemberBindRequest.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link MemberBindRequest.Head }
     *     
     */
    public MemberBindRequest.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberBindRequest.Head }
     *     
     */
    public void setHead(MemberBindRequest.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link MemberBindRequest.Body }
     *     
     */
    public MemberBindRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberBindRequest.Body }
     *     
     */
    public void setBody(MemberBindRequest.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bindflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="passwd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pwdquestion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pwdanswer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="listofcontact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contact" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="listofpersonaladdress">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "membid",
        "bindflg",
        "bindChannel",
        "bindTag"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected String bindflg;
        @XmlElement(required = true)
        protected String bindChannel;
        @XmlElement(required = true)
        protected String bindTag;
        
		/**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the bindflg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBindflg() {
            return bindflg;
        }

        /**
         * Sets the value of the bindflg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBindflg(String value) {
            this.bindflg = value;
        }

        public String getBindChannel() {
			return bindChannel;
		}

		public void setBindChannel(String bindChannel) {
			this.bindChannel = bindChannel;
		}

		public String getBindTag() {
			return bindTag;
		}

		public void setBindTag(String bindTag) {
			this.bindTag = bindTag;
		}



    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "reqtime",
        "systype"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String transcode;
        @XmlElement(required = true)
        protected String reqtime;
        @XmlElement(required = true)
        protected String systype;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranscode(String value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the reqtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqtime() {
            return reqtime;
        }

        /**
         * Sets the value of the reqtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqtime(String value) {
            this.reqtime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

    }

}
