//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 02:03:02 PM CST 
//


package com.jje.membercenter.xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="loypoint" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="cardstat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="listofcontact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contact">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="listofpersonaladdress">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="personaladdress" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="idustype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hobby" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="hobdesp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "response")
public class MemBaseQueryResponse {

    @XmlElement(required = true)
    protected MemBaseQueryResponse.Head head;
    @XmlElement(required = true)
    protected MemBaseQueryResponse.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link MemBaseQueryResponse.Head }
     *     
     */
    public MemBaseQueryResponse.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemBaseQueryResponse.Head }
     *     
     */
    public void setHead(MemBaseQueryResponse.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link MemBaseQueryResponse.Body }
     *     
     */
    public MemBaseQueryResponse.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemBaseQueryResponse.Body }
     *     
     */
    public void setBody(MemBaseQueryResponse.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="loypoint" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="cardstat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="listofcontact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contact">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="listofpersonaladdress">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="personaladdress" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                             &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="idustype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hobby" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="hobdesp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "membid",
        "loypoint",
        "cardstat",
        "listofcontact"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected BigInteger loypoint;
        @XmlElement(required = true)
        protected String cardstat;
        @XmlElement(required = true)
        protected MemBaseQueryResponse.Body.Listofcontact listofcontact;

        /**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the loypoint property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLoypoint() {
            return loypoint;
        }

        /**
         * Sets the value of the loypoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLoypoint(BigInteger value) {
            this.loypoint = value;
        }

        /**
         * Gets the value of the cardstat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardstat() {
            return cardstat;
        }

        /**
         * Sets the value of the cardstat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardstat(String value) {
            this.cardstat = value;
        }

        /**
         * Gets the value of the listofcontact property.
         * 
         * @return
         *     possible object is
         *     {@link MemBaseQueryResponse.Body.Listofcontact }
         *     
         */
        public MemBaseQueryResponse.Body.Listofcontact getListofcontact() {
            return listofcontact;
        }

        /**
         * Sets the value of the listofcontact property.
         * 
         * @param value
         *     allowed object is
         *     {@link MemBaseQueryResponse.Body.Listofcontact }
         *     
         */
        public void setListofcontact(MemBaseQueryResponse.Body.Listofcontact value) {
            this.listofcontact = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contact">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="listofpersonaladdress">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="personaladdress" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *                   &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="idustype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="hobby" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="hobdesp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contact"
        })
        public static class Listofcontact {

            @XmlElement(required = true)
            protected MemBaseQueryResponse.Body.Listofcontact.Contact contact;

            /**
             * Gets the value of the contact property.
             * 
             * @return
             *     possible object is
             *     {@link MemBaseQueryResponse.Body.Listofcontact.Contact }
             *     
             */
            public MemBaseQueryResponse.Body.Listofcontact.Contact getContact() {
                return contact;
            }

            /**
             * Sets the value of the contact property.
             * 
             * @param value
             *     allowed object is
             *     {@link MemBaseQueryResponse.Body.Listofcontact.Contact }
             *     
             */
            public void setContact(MemBaseQueryResponse.Body.Listofcontact.Contact value) {
                this.contact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="conpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="custtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="lifecycle" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="listofpersonaladdress">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="personaladdress" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="nation" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="hometown" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/>
             *         &lt;element name="cdtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cell" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="edulevl" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="idustype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="unit" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="cmpname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="preference" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="hobby" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="hobdesp" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "conpriflag",
                "lastname",
                "sex",
                "race",
                "custtype",
                "lifecycle",
                "language",
                "listofpersonaladdress",
                "title",
                "nation",
                "hometown",
                "birthday",
                "cdtype",
                "cdno",
                "email",
                "cell",
                "edulevl",
                "idustype",
                "unit",
                "position",
                "income",
                "cmpname",
                "married",
                "preference",
                "hobby",
                "hobdesp"
            })
            public static class Contact {

                @XmlElement(required = true)
                protected String conpriflag;
                @XmlElement(required = true)
                protected String lastname;
                @XmlElement(required = true)
                protected String sex;
                @XmlElement(required = true)
                protected String race;
                @XmlElement(required = true)
                protected String custtype;
                @XmlElement(required = true)
                protected String lifecycle;
                @XmlElement(required = true)
                protected String language;
                @XmlElement(required = true)
                protected MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress listofpersonaladdress;
                @XmlElement(required = true)
                protected String title;
                @XmlElement(required = true)
                protected String nation;
                @XmlElement(required = true)
                protected String hometown;
                @XmlElement(required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar birthday;
                @XmlElement(required = true)
                protected String cdtype;
                @XmlElement(required = true)
                protected String cdno;
                @XmlElement(required = true)
                protected String email;
                @XmlElement(required = true)
                protected String cell;
                @XmlElement(required = true)
                protected String edulevl;
                @XmlElement(required = true)
                protected String idustype;
                @XmlElement(required = true)
                protected String unit;
                @XmlElement(required = true)
                protected String position;
                @XmlElement(required = true)
                protected BigInteger income;
                @XmlElement(required = true)
                protected String cmpname;
                @XmlElement(required = true)
                protected String married;
                @XmlElement(required = true)
                protected String preference;
                @XmlElement(required = true)
                protected String hobby;
                @XmlElement(required = true)
                protected String hobdesp;

                /**
                 * Gets the value of the conpriflag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConpriflag() {
                    return conpriflag;
                }

                /**
                 * Sets the value of the conpriflag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConpriflag(String value) {
                    this.conpriflag = value;
                }

                /**
                 * Gets the value of the lastname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastname() {
                    return lastname;
                }

                /**
                 * Sets the value of the lastname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastname(String value) {
                    this.lastname = value;
                }

                /**
                 * Gets the value of the sex property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSex() {
                    return sex;
                }

                /**
                 * Sets the value of the sex property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSex(String value) {
                    this.sex = value;
                }

                /**
                 * Gets the value of the race property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRace() {
                    return race;
                }

                /**
                 * Sets the value of the race property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRace(String value) {
                    this.race = value;
                }

                /**
                 * Gets the value of the custtype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCusttype() {
                    return custtype;
                }

                /**
                 * Sets the value of the custtype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCusttype(String value) {
                    this.custtype = value;
                }

                /**
                 * Gets the value of the lifecycle property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLifecycle() {
                    return lifecycle;
                }

                /**
                 * Sets the value of the lifecycle property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLifecycle(String value) {
                    this.lifecycle = value;
                }

                /**
                 * Gets the value of the language property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguage() {
                    return language;
                }

                /**
                 * Sets the value of the language property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguage(String value) {
                    this.language = value;
                }

                /**
                 * Gets the value of the listofpersonaladdress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress }
                 *     
                 */
                public MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress getListofpersonaladdress() {
                    return listofpersonaladdress;
                }

                /**
                 * Sets the value of the listofpersonaladdress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress }
                 *     
                 */
                public void setListofpersonaladdress(MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress value) {
                    this.listofpersonaladdress = value;
                }

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }

                /**
                 * Gets the value of the nation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNation() {
                    return nation;
                }

                /**
                 * Sets the value of the nation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNation(String value) {
                    this.nation = value;
                }

                /**
                 * Gets the value of the hometown property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHometown() {
                    return hometown;
                }

                /**
                 * Sets the value of the hometown property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHometown(String value) {
                    this.hometown = value;
                }

                /**
                 * Gets the value of the birthday property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getBirthday() {
                    return birthday;
                }

                /**
                 * Sets the value of the birthday property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setBirthday(XMLGregorianCalendar value) {
                    this.birthday = value;
                }

                /**
                 * Gets the value of the cdtype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCdtype() {
                    return cdtype;
                }

                /**
                 * Sets the value of the cdtype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCdtype(String value) {
                    this.cdtype = value;
                }

                /**
                 * Gets the value of the cdno property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCdno() {
                    return cdno;
                }

                /**
                 * Sets the value of the cdno property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCdno(String value) {
                    this.cdno = value;
                }

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

                /**
                 * Gets the value of the cell property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCell() {
                    return cell;
                }

                /**
                 * Sets the value of the cell property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCell(String value) {
                    this.cell = value;
                }

                /**
                 * Gets the value of the edulevl property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEdulevl() {
                    return edulevl;
                }

                /**
                 * Sets the value of the edulevl property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEdulevl(String value) {
                    this.edulevl = value;
                }

                /**
                 * Gets the value of the idustype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdustype() {
                    return idustype;
                }

                /**
                 * Sets the value of the idustype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdustype(String value) {
                    this.idustype = value;
                }

                /**
                 * Gets the value of the unit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

                /**
                 * Gets the value of the position property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPosition() {
                    return position;
                }

                /**
                 * Sets the value of the position property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPosition(String value) {
                    this.position = value;
                }

                /**
                 * Gets the value of the income property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getIncome() {
                    return income;
                }

                /**
                 * Sets the value of the income property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setIncome(BigInteger value) {
                    this.income = value;
                }

                /**
                 * Gets the value of the cmpname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCmpname() {
                    return cmpname;
                }

                /**
                 * Sets the value of the cmpname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCmpname(String value) {
                    this.cmpname = value;
                }

                /**
                 * Gets the value of the married property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMarried() {
                    return married;
                }

                /**
                 * Sets the value of the married property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMarried(String value) {
                    this.married = value;
                }

                /**
                 * Gets the value of the preference property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPreference() {
                    return preference;
                }

                /**
                 * Sets the value of the preference property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPreference(String value) {
                    this.preference = value;
                }

                /**
                 * Gets the value of the hobby property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHobby() {
                    return hobby;
                }

                /**
                 * Sets the value of the hobby property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHobby(String value) {
                    this.hobby = value;
                }

                /**
                 * Gets the value of the hobdesp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHobdesp() {
                    return hobdesp;
                }

                /**
                 * Sets the value of the hobdesp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHobdesp(String value) {
                    this.hobdesp = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="personaladdress" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "personaladdress"
                })
                public static class Listofpersonaladdress {

                    @XmlElement(required = true)
                    protected List<MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress> personaladdress;

                    /**
                     * Gets the value of the personaladdress property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the personaladdress property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPersonaladdress().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress }
                     * 
                     * 
                     */
                    public List<MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress> getPersonaladdress() {
                        if (personaladdress == null) {
                            personaladdress = new ArrayList<MemBaseQueryResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress>();
                        }
                        return this.personaladdress;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="streetaddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "addpriflag",
                        "addrtype",
                        "address",
                        "province",
                        "city",
                        "area",
                        "streetaddr",
                        "postcode"
                    })
                    public static class Personaladdress {

                        @XmlElement(required = true)
                        protected String addpriflag;
                        @XmlElement(required = true)
                        protected String addrtype;
                        @XmlElement(required = true)
                        protected String address;
                        @XmlElement(required = true)
                        protected String province;
                        @XmlElement(required = true)
                        protected String city;
                        @XmlElement(required = true)
                        protected String area;
                        @XmlElement(required = true)
                        protected String streetaddr;
                        @XmlElement(required = true)
                        protected BigInteger postcode;

                        /**
                         * Gets the value of the addpriflag property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddpriflag() {
                            return addpriflag;
                        }

                        /**
                         * Sets the value of the addpriflag property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddpriflag(String value) {
                            this.addpriflag = value;
                        }

                        /**
                         * Gets the value of the addrtype property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddrtype() {
                            return addrtype;
                        }

                        /**
                         * Sets the value of the addrtype property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddrtype(String value) {
                            this.addrtype = value;
                        }

                        /**
                         * Gets the value of the address property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddress() {
                            return address;
                        }

                        /**
                         * Sets the value of the address property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddress(String value) {
                            this.address = value;
                        }

                        /**
                         * Gets the value of the province property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getProvince() {
                            return province;
                        }

                        /**
                         * Sets the value of the province property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setProvince(String value) {
                            this.province = value;
                        }

                        /**
                         * Gets the value of the city property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCity() {
                            return city;
                        }

                        /**
                         * Sets the value of the city property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCity(String value) {
                            this.city = value;
                        }

                        /**
                         * Gets the value of the area property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getArea() {
                            return area;
                        }

                        /**
                         * Sets the value of the area property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setArea(String value) {
                            this.area = value;
                        }

                        /**
                         * Gets the value of the streetaddr property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getStreetaddr() {
                            return streetaddr;
                        }

                        /**
                         * Sets the value of the streetaddr property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setStreetaddr(String value) {
                            this.streetaddr = value;
                        }

                        /**
                         * Gets the value of the postcode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getPostcode() {
                            return postcode;
                        }

                        /**
                         * Sets the value of the postcode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setPostcode(BigInteger value) {
                            this.postcode = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "reqtime",
        "systype",
        "retcode",
        "retmsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String transcode;
        @XmlElement(required = true)
        protected String reqtime;
        @XmlElement(required = true)
        protected String systype;
        @XmlElement(required = true)
        protected String retcode;
        @XmlElement(required = true)
        protected String retmsg;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranscode(String value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the reqtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqtime() {
            return reqtime;
        }

        /**
         * Sets the value of the reqtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqtime(String value) {
            this.reqtime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

        /**
         * Gets the value of the retcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetcode() {
            return retcode;
        }

        /**
         * Sets the value of the retcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetcode(String value) {
            this.retcode = value;
        }

        /**
         * Gets the value of the retmsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetmsg() {
            return retmsg;
        }

        /**
         * Sets the value of the retmsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetmsg(String value) {
            this.retmsg = value;
        }

    }

}
