//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 02:50:23 PM CST 
//


package com.jje.membercenter.xsd;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang.math.NumberUtils;

import com.jje.common.utils.DateUtils;
import com.jje.dto.membercenter.MemberDto;
import com.jje.dto.membercenter.MemberMemCardDto;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "response")
public class MemberRegisterResponse {

    @XmlElement(required = true)
    protected MemberRegisterResponse.Head head;
    @XmlElement(required = true)
    protected MemberRegisterResponse.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link MemberRegisterResponse.Head }
     *     
     */
    public MemberRegisterResponse.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberRegisterResponse.Head }
     *     
     */
    public void setHead(MemberRegisterResponse.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link MemberRegisterResponse.Body }
     *     
     */
    public MemberRegisterResponse.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberRegisterResponse.Body }
     *     
     */
    public void setBody(MemberRegisterResponse.Body value) {
        this.body = value;
    }
    
    public static MemberDto getMemberDtoByBody(MemberRegisterResponse.Body body) {
		MemberDto dto = new MemberDto();
		dto.setFullName(body.getRecord().getMember().getFullName());
		dto.setIdentityNo(body.getRecord().getMember().getCDNumber());
		dto.setIdentityType(body.getRecord().getMember().getCDType());
		dto.setCellPhone(body.getRecord().getMember().getCellPhone());
		dto.setEmail(body.getRecord().getMember().getEmail());
		dto.setLastUpd(DateUtils.parseDate(body.getRecord().getMember().getLastUpdDate(), "MM/dd/yyyy"));
		dto.setMemberHierarchy(body.getRecord().getMember().getMemberHierarchy());
		dto.setMemberID(body.getMembid());
		dto.setMemberType(body.getRecord().getMember().getMemberType());
		dto.setTitle(body.getRecord().getMember().getMemberTitle());
		dto.setPassword(body.getRecord().getMember().getPassword());
		dto.setRegisterDate(DateUtils.parseDate(body.getRecord().getMember().getRegisterDate(), "MM/dd/yyyy"));
		dto.setRegisterSource(body.getRecord().getMember().getRegisterSource());
		dto.setRegisterTag(body.getRecord().getMember().getRegisterSourceTag());
		dto.setRemindAnswer(body.getRecord().getMember().getRemindAnswer());
		dto.setRemindQuestion(body.getRecord().getMember().getRemindQuestion());
		dto.setStatus(body.getRecord().getMember().getStatus());
		dto.setThirdpartyType(body.getRecord().getMember().getThirdpartyType());
		dto.setCardList(body.getRecord().getMember().getListofcard().getMemberCardList());
		dto.setMemberCode(body.getRecord().getMember().getMemberCode());
		dto.setActivateCode(body.getRecord().getMember().getJJBEActivateCode());
		dto.setCardNo(body.getRecord().getMember().getJJBECardNumber());
		dto.setCardLevel(body.getRecord().getMember().getCardLevel());
		dto.setScoreType(NumberUtils.toInt(body.getRecord().getMember().getJJBEConvertFlag()));
		return dto;
	}
    
    public static class CardInfo {
    	String cardStatus; // 卡状态
		String cardType; // 卡类型
		String cardExpireDate; // 卡到期时间
    	String cardNumber; // 卡号
    	String cardStartDate; // 卡开始时间
    	String tierName;//会员层级,Silver	银卡,Gold	金卡,Platinum	铂金卡,Black	黑卡



        public String getCardStatus() {
			return cardStatus;
		}

		public void setCardStatus(String cardStatus) {
			this.cardStatus = cardStatus;
		}

		public String getCardExpireDate() {
			return cardExpireDate;
		}

		public void setCardExpireDate(String cardExpireDate) {
			this.cardExpireDate = cardExpireDate;
		}

		public String getCardNumber() {
			return cardNumber;
		}

		public void setCardNumber(String cardNumber) {
			this.cardNumber = cardNumber;
		}

		public String getCardStartDate() {
			return cardStartDate;
		}

		public void setCardStartDate(String cardStartDate) {
			this.cardStartDate = cardStartDate;
		}


    	public String getCardType() {
			return cardType;
		}

		public void setCardType(String cardType) {
			this.cardType = cardType;
		}

        public String getTierName() {
            return tierName;
        }

        public void setTierName(String tierName) {
            this.tierName = tierName;
        }
    }



    public static class Record {

        public void setMember(Member member) {
            this.member = member;
        }

        public static class Member {
        	protected String JJBEActivateCode; // 是否激活
			protected String JJBECardNumber; // 会员卡号（礼卡）
        	protected String JJBEConvertFlag; // 是否累计合作伙伴积分 Y 是累计，否则是不累计
			protected String fullName; // 会员姓名
            protected String CDType; // 证件类型
            protected String CDNumber; // 证件号
            protected String password; // 密码
            protected String remindAnswer; // 密码提示问题答案
            protected String remindQuestion; // 密码提示问题
            protected String cardLevel; // 最高层级
            protected String cellPhone; // 手机号
            protected String email; // 邮箱
            protected String lastUpdDate; // 最后更新日期
            protected String memberCode; // 会员编号
            protected String memberHierarchy; // 层级
            protected String memberType; // 会员状态（活跃或已合并）
            protected String memberTitle; // 性别
            protected String registerDate; // 注册日期
            protected String registerSource; // 注册渠道
            protected String registerSourceTag; // 注册子渠道
            protected String status; // 会员状态
            protected String thirdpartyType; // 优惠券够买享卡时活动类型
            protected Listofcard listofcard;
            
        	public String getJJBEActivateCode() {
				return JJBEActivateCode;
			}
			public void setJJBEActivateCode(String jJBEActivateCode) {
				JJBEActivateCode = jJBEActivateCode;
			}

			public String getJJBECardNumber() {
				return JJBECardNumber;
			}
			public void setJJBECardNumber(String jJBECardNumber) {
				JJBECardNumber = jJBECardNumber;
			}
			public String getCDType() {
				return CDType;
			}
			public void setCDType(String cDType) {
				CDType = cDType;
			}
			public String getCDNumber() {
				return CDNumber;
			}
			public void setCDNumber(String cDNumber) {
				CDNumber = cDNumber;
			}
			public String getJJBEConvertFlag() {
				return JJBEConvertFlag;
			}
			public void setJJBEConvertFlag(String jJBEConvertFlag) {
				JJBEConvertFlag = jJBEConvertFlag;
			}
            public Listofcard getListofcard() {
                return listofcard;
            }
            public void setListofcard(Listofcard listofcard) {
                this.listofcard = listofcard;
            }
            public static class Listofcard{



                public List<CardInfo> getCardlist() {
                    return cardlist;
                }

                public void setCardlist(List<CardInfo> cardlist) {
                    this.cardlist = cardlist;
                }

                protected List<CardInfo> cardlist;

                public List<CardInfo> getCardList() {
                    return cardlist;
                }

                public List<MemberMemCardDto> getMemberCardList() {
                    List<MemberMemCardDto> list = new ArrayList<MemberMemCardDto>();
                    if(cardlist == null) {
                        return list;
                    }
                    for(CardInfo cardInfo : cardlist) {
                        MemberMemCardDto dto = new MemberMemCardDto();
                        
                        
                        if(cardInfo.getCardType()!=null && !"".equals(cardInfo.getCardType())){
                        	dto.setCardTypeCd(cardInfo.getCardType());
                        }else  if(cardInfo.getTierName()!=null && !"".equals(cardInfo.getTierName())){
                        	dto.setCardTypeCd(cardInfo.getTierName());
                        }else{
                        	dto.setCardTypeCd("none");
                        }
                        dto.setStatus(cardInfo.getCardStatus());
                        dto.setxCardNum(cardInfo.getCardNumber());
                        dto.setValidDate(DateUtils.parseDate(cardInfo.getCardStartDate(), "MM/dd/yyyy"));
                        dto.setDueDate(DateUtils.parseDate(cardInfo.getCardExpireDate(), "MM/dd/yyyy"));
                        list.add(dto);
                    }
                    return list;
                }

                public void setCardList(List<CardInfo> cardList) {
                    this.cardlist = cardList;
                }


            }

            public String getFullName() {
                return fullName;
            }
            public void setFullName(String fullName) {
                this.fullName = fullName;
            }
            public String getPassword() {
                return password;
            }
            public void setPassword(String password) {
                this.password = password;
            }
            public String getRemindAnswer() {
                return remindAnswer;
            }
            public void setRemindAnswer(String remindAnswer) {
                this.remindAnswer = remindAnswer;
            }
            public String getRemindQuestion() {
                return remindQuestion;
            }
            public void setRemindQuestion(String remindQuestion) {
                this.remindQuestion = remindQuestion;
            }
            public String getCardLevel() {
                return cardLevel;
            }
            public void setCardLevel(String cardLevel) {
                this.cardLevel = cardLevel;
            }
            public String getCellPhone() {
                return cellPhone;
            }
            public void setCellPhone(String cellPhone) {
                this.cellPhone = cellPhone;
            }
            public String getEmail() {
                return email;
            }
            public void setEmail(String email) {
                this.email = email;
            }
            public String getLastUpdDate() {
                return lastUpdDate;
            }
            public void setLastUpdDate(String lastUpdDate) {
                this.lastUpdDate = lastUpdDate;
            }
            public String getMemberCode() {
                return memberCode;
            }
            public void setMemberCode(String memberCode) {
                this.memberCode = memberCode;
            }
            public String getMemberHierarchy() {
                return memberHierarchy;
            }
            public void setMemberHierarchy(String memberHierarchy) {
                this.memberHierarchy = memberHierarchy;
            }
            public String getMemberType() {
                return memberType;
            }
            public void setMemberType(String memberType) {
                this.memberType = memberType;
            }
            public String getMemberTitle() {
                return memberTitle;
            }
            public void setMemberTitle(String memberTitle) {
                this.memberTitle = memberTitle;
            }
            public String getRegisterDate() {
                return registerDate;
            }
            public void setRegisterDate(String registerDate) {
                this.registerDate = registerDate;
            }
            public String getRegisterSource() {
                return registerSource;
            }
            public void setRegisterSource(String registerSource) {
                this.registerSource = registerSource;
            }
            public String getRegisterSourceTag() {
                return registerSourceTag;
            }
            public void setRegisterSourceTag(String registerSourceTag) {
                this.registerSourceTag = registerSourceTag;
            }
            public String getStatus() {
                return status;
            }
            public void setStatus(String status) {
                this.status = status;
            }
            public String getThirdpartyType() {
                return thirdpartyType;
            }
            public void setThirdpartyType(String thirdpartyType) {
                this.thirdpartyType = thirdpartyType;
            }
        }

        protected MemberRegisterResponse.Record.Member member;

        public MemberRegisterResponse.Record.Member getMember() {
            return member;
        }
    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
//    @XmlType(name = "", propOrder = {
//        "membid",
//        "recode",
//        "remsg"
//    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected String recode;
        @XmlElement(required = true)
        protected String remsg;
        @XmlElement(required = true)
        protected MemberRegisterResponse.Record record;

        public void setRecord(Record record) {
            this.record = record;
        }

        public MemberRegisterResponse.Record getRecord() {
			return record;
		}



    	
        

        /**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the recode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public String getRecode() {
            return recode;
        }

        /**
         * Sets the value of the recode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRecode(String value) {
            this.recode = value;
        }

        /**
         * Gets the value of the remsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemsg() {
            return remsg;
        }

        /**
         * Sets the value of the remsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemsg(String value) {
            this.remsg = value;
        }
    }
 
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "resptime",
        "systype",
        "retcode",
        "retmsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected BigInteger transcode;
        @XmlElement(required = true)
        protected BigInteger resptime;
        @XmlElement(required = true)
        protected String systype;
        @XmlElement(required = true)
        protected BigInteger retcode;
        @XmlElement(required = true)
        protected String retmsg;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTranscode(BigInteger value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the resptime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getResptime() {
            return resptime;
        }

        /**
         * Sets the value of the resptime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setResptime(BigInteger value) {
            this.resptime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

        /**
         * Gets the value of the retcode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRetcode() {
            return retcode;
        }

        /**
         * Sets the value of the retcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRetcode(BigInteger value) {
            this.retcode = value;
        }

        /**
         * Gets the value of the retmsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetmsg() {
            return retmsg;
        }

        /**
         * Sets the value of the retmsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetmsg(String value) {
            this.retmsg = value;
        }
        
        

    }

    
	public boolean isExecSuccess() {
		return this.getBody()==null?false:this.body.getRecode().toString().equals("00001");
	}

}
