//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.26 at 03:56:52 PM CST 
//


package com.jje.membercenter.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="listofcontact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contact">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="listofpersonaladdress">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "response")
public class MemberAddressResponse {

    @XmlElement(required = true)
    protected MemberAddressResponse.Head head;
    @XmlElement(required = true)
    protected MemberAddressResponse.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link MemberAddressResponse.Head }
     *     
     */
    public MemberAddressResponse.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberAddressResponse.Head }
     *     
     */
    public void setHead(MemberAddressResponse.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link MemberAddressResponse.Body }
     *     
     */
    public MemberAddressResponse.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberAddressResponse.Body }
     *     
     */
    public void setBody(MemberAddressResponse.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="listofcontact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contact">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="listofpersonaladdress">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "membid",
        "listofcontact"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected MemberAddressResponse.Body.Listofcontact listofcontact;

        /**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the listofcontact property.
         * 
         * @return
         *     possible object is
         *     {@link MemberAddressResponse.Body.Listofcontact }
         *     
         */
        public MemberAddressResponse.Body.Listofcontact getListofcontact() {
            return listofcontact;
        }

        /**
         * Sets the value of the listofcontact property.
         * 
         * @param value
         *     allowed object is
         *     {@link MemberAddressResponse.Body.Listofcontact }
         *     
         */
        public void setListofcontact(MemberAddressResponse.Body.Listofcontact value) {
            this.listofcontact = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contact">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="listofpersonaladdress">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contact"
        })
        public static class Listofcontact {

            @XmlElement(required = true)
            protected MemberAddressResponse.Body.Listofcontact.Contact contact;

            /**
             * Gets the value of the contact property.
             * 
             * @return
             *     possible object is
             *     {@link MemberAddressResponse.Body.Listofcontact.Contact }
             *     
             */
            public MemberAddressResponse.Body.Listofcontact.Contact getContact() {
                return contact;
            }

            /**
             * Sets the value of the contact property.
             * 
             * @param value
             *     allowed object is
             *     {@link MemberAddressResponse.Body.Listofcontact.Contact }
             *     
             */
            public void setContact(MemberAddressResponse.Body.Listofcontact.Contact value) {
                this.contact = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="listofpersonaladdress">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lastname",
                "listofpersonaladdress"
            })
            public static class Contact {

                @XmlElement(required = true)
                protected String lastname;
                @XmlElement(required = true)
                protected MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress listofpersonaladdress;

                /**
                 * Gets the value of the lastname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastname() {
                    return lastname;
                }

                /**
                 * Sets the value of the lastname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastname(String value) {
                    this.lastname = value;
                }

                /**
                 * Gets the value of the listofpersonaladdress property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress }
                 *     
                 */
                public MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress getListofpersonaladdress() {
                    return listofpersonaladdress;
                }

                /**
                 * Sets the value of the listofpersonaladdress property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress }
                 *     
                 */
                public void setListofpersonaladdress(MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress value) {
                    this.listofpersonaladdress = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="personaladdress" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "personaladdress"
                })
                public static class Listofpersonaladdress {

                    protected List<MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress> personaladdress;

                    /**
                     * Gets the value of the personaladdress property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the personaladdress property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPersonaladdress().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress }
                     * 
                     * 
                     */
                    public List<MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress> getPersonaladdress() {
                        if (personaladdress == null) {
                            personaladdress = new ArrayList<MemberAddressResponse.Body.Listofcontact.Contact.Listofpersonaladdress.Personaladdress>();
                        }
                        return this.personaladdress;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="addrnumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="addpriflag" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="addrtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="province" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="updt" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "addrnumber",
                        "addpriflag",
                        "addrtype",
                        "addr",
                        "continent",
                        "state",
                        "province",
                        "city",
                        "area",
                        "street",
                        "postcode",
                        "updt"
                    })
                    public static class Personaladdress {

                        @XmlElement(required = true)
                        protected String addrnumber;
                        @XmlElement(required = true)
                        protected String addpriflag;
                        @XmlElement(required = true)
                        protected String addrtype;
                        @XmlElement(required = true)
                        protected String addr;
                        @XmlElement(required = true)
                        protected String continent;
                        @XmlElement(required = true)
                        protected String state;
                        @XmlElement(required = true)
                        protected String province;
                        @XmlElement(required = true)
                        protected String city;
                        @XmlElement(required = true)
                        protected String area;
                        @XmlElement(required = true)
                        protected String street;
                        @XmlElement(required = true)
                        protected String postcode;
                        @XmlElement(required = true)
                        protected String updt;

                        /**
                         * Gets the value of the addrnumber property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddrnumber() {
                            return addrnumber;
                        }

                        /**
                         * Sets the value of the addrnumber property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddrnumber(String value) {
                            this.addrnumber = value;
                        }

                        /**
                         * Gets the value of the addpriflag property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddpriflag() {
                            return addpriflag;
                        }

                        /**
                         * Sets the value of the addpriflag property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddpriflag(String value) {
                            this.addpriflag = value;
                        }

                        /**
                         * Gets the value of the addrtype property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddrtype() {
                            return addrtype;
                        }

                        /**
                         * Sets the value of the addrtype property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddrtype(String value) {
                            this.addrtype = value;
                        }

                        /**
                         * Gets the value of the addr property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAddr() {
                            return addr;
                        }

                        /**
                         * Sets the value of the addr property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAddr(String value) {
                            this.addr = value;
                        }

                        /**
                         * Gets the value of the continent property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getContinent() {
                            return continent;
                        }

                        /**
                         * Sets the value of the continent property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setContinent(String value) {
                            this.continent = value;
                        }

                        /**
                         * Gets the value of the state property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getState() {
                            return state;
                        }

                        /**
                         * Sets the value of the state property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setState(String value) {
                            this.state = value;
                        }

                        /**
                         * Gets the value of the province property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getProvince() {
                            return province;
                        }

                        /**
                         * Sets the value of the province property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setProvince(String value) {
                            this.province = value;
                        }

                        /**
                         * Gets the value of the city property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCity() {
                            return city;
                        }

                        /**
                         * Sets the value of the city property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCity(String value) {
                            this.city = value;
                        }

                        /**
                         * Gets the value of the area property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getArea() {
                            return area;
                        }

                        /**
                         * Sets the value of the area property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setArea(String value) {
                            this.area = value;
                        }

                        /**
                         * Gets the value of the street property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getStreet() {
                            return street;
                        }

                        /**
                         * Sets the value of the street property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setStreet(String value) {
                            this.street = value;
                        }

                        /**
                         * Gets the value of the postcode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPostcode() {
                            return postcode;
                        }

                        /**
                         * Sets the value of the postcode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPostcode(String value) {
                            this.postcode = value;
                        }

                        /**
                         * Gets the value of the updt property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUpdt() {
                            return updt;
                        }

                        /**
                         * Sets the value of the updt property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUpdt(String value) {
                            this.updt = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="retmsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "reqtime",
        "systype",
        "retcode",
        "retmsg"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String transcode;
        @XmlElement(required = true)
        protected String reqtime;
        @XmlElement(required = true)
        protected String systype;
        @XmlElement(required = true)
        protected String retcode;
        @XmlElement(required = true)
        protected String retmsg;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranscode(String value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the reqtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqtime() {
            return reqtime;
        }

        /**
         * Sets the value of the reqtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqtime(String value) {
            this.reqtime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

        /**
         * Gets the value of the retcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetcode() {
            return retcode;
        }

        /**
         * Sets the value of the retcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetcode(String value) {
            this.retcode = value;
        }

        /**
         * Gets the value of the retmsg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRetmsg() {
            return retmsg;
        }

        /**
         * Sets the value of the retmsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRetmsg(String value) {
            this.retmsg = value;
        }

    }

}
