//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.08 at 04:55:27 PM CST 
//


package com.jje.membercenter.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="head">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="membcdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="optype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="buydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vipstore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="salesperson" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="salesmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="postflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="invflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "body"
})
@XmlRootElement(name = "request")
public class SynRightCardRequest {

    @XmlElement(required = true)
    protected SynRightCardRequest.Head head;
    @XmlElement(required = true)
    protected SynRightCardRequest.Body body;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link SynRightCardRequest.Head }
     *     
     */
    public SynRightCardRequest.Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynRightCardRequest.Head }
     *     
     */
    public void setHead(SynRightCardRequest.Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link SynRightCardRequest.Body }
     *     
     */
    public SynRightCardRequest.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynRightCardRequest.Body }
     *     
     */
    public void setBody(SynRightCardRequest.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="membid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="membcdno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="optype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="buydate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="vipstore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="salesperson" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="salesmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="postflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="invflg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "membid",
        "membcdno",
        "optype",
        "buydate",
        "channel",
        "vipstore",
        "salesperson",
        "salesmount",
        "desc",
        "postflg",
        "invflg",
        "activityType"
    })
    public static class Body {

        @XmlElement(required = true)
        protected String membid;
        @XmlElement(required = true)
        protected String membcdno;
        @XmlElement(required = true)
        protected String optype;
        @XmlElement(required = true)
        protected String buydate;
        @XmlElement(required = true)
        protected String channel;
        @XmlElement(required = true)
        protected String vipstore;
        @XmlElement(required = true)
        protected String salesperson;
        @XmlElement(required = true)
        protected String salesmount;
        @XmlElement(required = true)
        protected String desc;
        @XmlElement(required = true)
        protected String postflg;
        @XmlElement(required = true)
        protected String invflg;
        @XmlElement(required = false)
        protected String activityType;

        public String getActivityType() {
			return activityType;
		}

		public void setActivityType(String activityType) {
			this.activityType = activityType;
		}

        /**
         * Gets the value of the membid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembid() {
            return membid;
        }

        /**
         * Sets the value of the membid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembid(String value) {
            this.membid = value;
        }

        /**
         * Gets the value of the membcdno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMembcdno() {
            return membcdno;
        }

        /**
         * Sets the value of the membcdno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMembcdno(String value) {
            this.membcdno = value;
        }

        /**
         * Gets the value of the optype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOptype() {
            return optype;
        }

        /**
         * Sets the value of the optype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOptype(String value) {
            this.optype = value;
        }

        /**
         * Gets the value of the buydate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuydate() {
            return buydate;
        }

        /**
         * Sets the value of the buydate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuydate(String value) {
            this.buydate = value;
        }

        /**
         * Gets the value of the channel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannel() {
            return channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannel(String value) {
            this.channel = value;
        }

        /**
         * Gets the value of the vipstore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVipstore() {
            return vipstore;
        }

        /**
         * Sets the value of the vipstore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVipstore(String value) {
            this.vipstore = value;
        }

        /**
         * Gets the value of the salesperson property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSalesperson() {
            return salesperson;
        }

        /**
         * Sets the value of the salesperson property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSalesperson(String value) {
            this.salesperson = value;
        }

        /**
         * Gets the value of the salesmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSalesmount() {
            return salesmount;
        }

        /**
         * Sets the value of the salesmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSalesmount(String value) {
            this.salesmount = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the postflg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostflg() {
            return postflg;
        }

        /**
         * Sets the value of the postflg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostflg(String value) {
            this.postflg = value;
        }

        /**
         * Gets the value of the invflg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvflg() {
            return invflg;
        }

        /**
         * Sets the value of the invflg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvflg(String value) {
            this.invflg = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="transcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reqtime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="systype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transcode",
        "reqtime",
        "systype"
    })
    public static class Head {

        @XmlElement(required = true)
        protected String transcode;
        @XmlElement(required = true)
        protected String reqtime;
        @XmlElement(required = true)
        protected String systype;

        /**
         * Gets the value of the transcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranscode() {
            return transcode;
        }

        /**
         * Sets the value of the transcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranscode(String value) {
            this.transcode = value;
        }

        /**
         * Gets the value of the reqtime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReqtime() {
            return reqtime;
        }

        /**
         * Sets the value of the reqtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReqtime(String value) {
            this.reqtime = value;
        }

        /**
         * Gets the value of the systype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSystype() {
            return systype;
        }

        /**
         * Sets the value of the systype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSystype(String value) {
            this.systype = value;
        }

    }

}
