//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.17 at 02:32:08 下午 CST 
//


package com.jje.membercenter.account.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jje.membercenter.account.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jje.membercenter.account.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccountActivationRequest }
     * 
     */
    public AccountActivationRequest createRequest() {
        return new AccountActivationRequest();
    }

    /**
     * Create an instance of {@link AccountActivationRequest.Head }
     * 
     */
    public AccountActivationRequest.Head createRequestHead() {
        return new AccountActivationRequest.Head();
    }

    /**
     * Create an instance of {@link AccountActivationResponse }
     * 
     */
    public AccountActivationResponse createResponse() {
        return new AccountActivationResponse();
    }

    /**
     * Create an instance of {@link AccountActivationResponse.Head }
     * 
     */
    public AccountActivationResponse.Head createResponseHead() {
        return new AccountActivationResponse.Head();
    }

    /**
     * Create an instance of {@link AccountActivationResponse.Body }
     * 
     */
    public AccountActivationResponse.Body createResponseBody() {
        return new AccountActivationResponse.Body();
    }

    /**
     * Create an instance of {@link AccountActivationRequest.Body }
     * 
     */
    public AccountActivationRequest.Body createRequestBody() {
        return new AccountActivationRequest.Body();
    }

}
