DELETE from T_VBP_MEMBER_TAOBAO_BINDING;

insert into T_VBP_MEMBER_TAOBAO_BINDING ( ID, MEMBER_ID, TAOBAO_ID, STATUS ) values ( 100, '3', '100', 'UNBIND' );
insert into T_VBP_MEMBER_TAOBAO_BINDING ( ID, MEMBER_ID, TAOBAO_ID, STATUS ) values ( 101, '3', '101', 'UNBIND' );
insert into T_VBP_MEMBER_TAOBAO_BINDING ( ID, MEMBER_ID, TAOBAO_ID, STATUS ) values ( 102, '4', '102', 'BINDED' );

